pub mod kv_cache;
pub mod two_phase;
pub mod sampling;
pub mod generator;
pub mod logit_processors;
pub mod prompt_templates;
pub mod context_extension;
pub mod rag;
pub mod unified_generator;
pub mod decs;
pub mod hull_kv_cache;
pub mod llm_computer;
pub mod token_merging;
pub mod matryoshka;
pub mod paca;
pub mod tool_search;
pub mod speculative;
pub mod paged_attention;
pub mod cross_modal;
pub mod circular_kv;
pub mod video_compression;
pub mod host_tools;
pub mod lsp_tools;
pub mod wasm_sandbox;
pub mod mirror_test;
pub mod block_draft;
pub mod concept_memory;
pub mod pdf_ingestion;
pub mod acp;
pub mod tts_stream;
pub mod vla;

pub use kv_cache::{LayerKVCache, ModelKVCache};
pub use two_phase::{TwoPhaseConfig, TwoPhaseInference, KVCache, Sampler, GenerationState};
pub use generator::{TokenGenerator, GenerateConfig};
pub use logit_processors::{LogitProcessor, LogitProcessorConfig, TokenHistory};
pub use prompt_templates::{PromptTemplateRegistry, TemplateFormat, ChatMessage, Role};
pub use context_extension::{ContextExtensionConfig, ContextExtensionEngine, ExtensionMethod, YarnParams, AttentionSinkManager};
pub use rag::{RagStore, RagConfig, Document, RetrievedDocument, RetrievalMethod, InContextLearner, cosine_similarity};
pub use tool_search::{ToolRegistry, ToolSearchConfig, Tool, SelectedTool, ToolCall, ToolResult};
pub use decs::{DecsOptimizer, DecsConfig, ReasoningChain, ReasoningMetrics, StopReason};
pub use hull_kv_cache::{HullKVCache, Point2D, Attention2D};
pub use llm_computer::{LlmComputer, LlmComputerConfig, CalmInstruction, CalmOp, VmState};
pub use sampling::{sample_argmax, sample_temperature, sample_top_k, sample_top_p};
pub use token_merging::{ToMeMerger, ToMeConfig, TokenSizes, cosine_sim};
pub use matryoshka::ElasticRagStore;
pub use paca::{PacaEngine, PacaConfig, ClusterMethod, ClusterAssignment};
