//! Tool Creation Pipeline — Model Generates Its Own Tools
//!
//! Based on Voyager skill library, LATM (LLMs as Tool Makers), and CREATOR.
//! The model encounters a problem it can't solve directly, generates a tool
//! specification, the WasmSandbox validates it, MirrorTest evaluates quality,
//! and if it passes, the tool is registered in the ToolRegistry.
//!
//! Pipeline:
//!   1. Model emits [tool_create] specification (name, params, returns, code)
//!   2. WasmSandbox compiles and validates the code
//!   3. MirrorTest generates test cases and validates I/O
//!   4. If quality passes threshold → register in ToolRegistry
//!   5. If quality fails → feed error back to model for repair
//!   6. Max 3 refinement iterations before giving up

use std::collections::HashMap;

// ---------------------------------------------------------------------------
// Tool specification
// ---------------------------------------------------------------------------

/// A tool specification generated by the model.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ToolSpec {
    /// Unique name for the tool.
    pub name: String,
    /// Human-readable description.
    pub description: String,
    /// Parameter types, e.g. "input: string, count: number"
    pub parameters: String,
    /// Return type, e.g. "array of objects"
    pub returns: String,
    /// The tool's implementation code (DSL or WASM subset).
    pub code: String,
    /// Category for tool search indexing.
    pub category: String,
    /// Tags for retrieval.
    pub tags: Vec<String>,
}

impl ToolSpec {
    /// Create a minimal tool spec.
    pub fn new(name: impl Into<String>, description: impl Into<String>, code: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            description: description.into(),
            parameters: String::new(),
            returns: String::new(),
            code: code.into(),
            category: "generated".to_string(),
            tags: vec!["auto-generated".into()],
        }
    }

    /// Parse a tool spec from a model's [tool_create] block.
    ///
    /// Expected format:
    /// ```text
    /// [tool_create]
    /// name: parse_csv
    /// description: Parse CSV string into rows
    /// params: input: string
    /// returns: array
    /// category: parser
    /// ---
    /// fn parse_csv(s) { ... }
    /// [/tool_create]
    /// ```
    pub fn parse_from_output(output: &str) -> Option<Self> {
        let start = output.find("[tool_create]")?;
        let end = output.find("[/tool_create]")?;
        let body = &output[start + "[tool_create]".len()..end];

        let mut name = String::new();
        let mut description = String::new();
        let mut parameters = String::new();
        let mut returns = String::new();
        let mut category = "generated".to_string();
        let mut tags = vec!["auto-generated".to_string()];
        let mut code_lines: Vec<String> = Vec::new();
        let mut in_code = false;

        for line in body.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("---") {
                in_code = true;
                continue;
            }
            if in_code {
                code_lines.push(line.to_string());
            } else if let Some(val) = trimmed.strip_prefix("name:") {
                name = val.trim().to_string();
            } else if let Some(val) = trimmed.strip_prefix("description:") {
                description = val.trim().to_string();
            } else if let Some(val) = trimmed.strip_prefix("params:") {
                parameters = val.trim().to_string();
            } else if let Some(val) = trimmed.strip_prefix("returns:") {
                returns = val.trim().to_string();
            } else if let Some(val) = trimmed.strip_prefix("category:") {
                category = val.trim().to_string();
            } else if let Some(val) = trimmed.strip_prefix("tags:") {
                tags = val.split(',')
                    .map(|t| t.trim().to_string())
                    .filter(|t| !t.is_empty())
                    .collect();
            }
        }

        if name.is_empty() || code_lines.is_empty() {
            return None;
        }

        Some(Self {
            name,
            description,
            parameters,
            returns,
            code: code_lines.join("\n"),
            category,
            tags,
        })
    }
}

// ---------------------------------------------------------------------------
// Validation result
// ---------------------------------------------------------------------------

/// Result of validating a tool spec.
#[derive(Debug, Clone)]
pub struct ValidationResult {
    /// Whether the tool passed validation.
    pub passed: bool,
    /// Overall quality score (0.0–1.0).
    pub quality: f32,
    /// Individual validation checks.
    pub checks: Vec<ValidationCheck>,
    /// Errors encountered during validation.
    pub errors: Vec<String>,
    /// Warnings (non-fatal issues).
    pub warnings: Vec<String>,
}

impl ValidationResult {
    #[allow(dead_code)]
    fn passed() -> Self {
        Self {
            passed: true,
            quality: 1.0,
            checks: vec![],
            errors: vec![],
            warnings: vec![],
        }
    }

    #[allow(dead_code)]
    fn failed(errors: Vec<String>) -> Self {
        Self {
            passed: false,
            quality: 0.0,
            checks: vec![],
            errors,
            warnings: vec![],
        }
    }
}

/// A single validation check.
#[derive(Debug, Clone)]
pub struct ValidationCheck {
    pub name: String,
    pub passed: bool,
    pub score: f32,
    pub message: String,
}

// ---------------------------------------------------------------------------
// Tool creation attempt
// ---------------------------------------------------------------------------

/// Record of a single tool creation attempt.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct CreationAttempt {
    /// Attempt number (1-indexed).
    pub attempt: usize,
    /// The spec that was submitted.
    pub spec: ToolSpec,
    /// Quality score achieved.
    pub quality: f32,
    /// Whether this attempt succeeded.
    pub success: bool,
    /// Error messages (if any).
    pub errors: Vec<String>,
    /// Timestamp.
    pub timestamp: u64,
}

// ---------------------------------------------------------------------------
// Tool creation configuration
// ---------------------------------------------------------------------------

/// Configuration for the tool creation pipeline.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ToolCreationConfig {
    /// Minimum quality score to accept a created tool.
    pub quality_threshold: f32,
    /// Maximum refinement attempts per tool.
    pub max_attempts: usize,
    /// Maximum code length in bytes.
    pub max_code_bytes: usize,
    /// Banned names (reserved tools).
    pub reserved_names: Vec<String>,
    /// Enable syntax validation via WASM sandbox.
    pub validate_syntax: bool,
    /// Enable semantic validation via mirror test.
    pub validate_semantics: bool,
    /// Maximum execution time per test (ms).
    pub max_execution_ms: u64,
}

impl Default for ToolCreationConfig {
    fn default() -> Self {
        Self {
            quality_threshold: 0.7,
            max_attempts: 3,
            max_code_bytes: 4096,
            reserved_names: vec![
                "calm_execute".into(),
                "mirror_test".into(),
                "concept_lookup".into(),
                "learn".into(),
            ],
            validate_syntax: true,
            validate_semantics: true,
            max_execution_ms: 100,
        }
    }
}

// ---------------------------------------------------------------------------
// ToolCreationPipeline
// ---------------------------------------------------------------------------

/// Pipeline for creating, validating, and registering tools from model output.
///
/// The pipeline:
/// 1. Parses tool specifications from model output
/// 2. Validates syntax (WASM sandbox or structural checks)
/// 3. Validates semantics (mirror test or functional checks)
/// 4. Registers passing tools in the tool registry
/// 5. Tracks creation attempts for learning
pub struct ToolCreationPipeline {
    config: ToolCreationConfig,
    /// History of all creation attempts.
    attempts: Vec<CreationAttempt>,
    /// Currently registered created tools (name → spec).
    created_tools: HashMap<String, ToolSpec>,
    /// Counter for unique tool IDs.
    next_id: u64,
}

impl ToolCreationPipeline {
    /// Create a new pipeline with the given configuration.
    pub fn new(config: ToolCreationConfig) -> Self {
        Self {
            config,
            attempts: Vec::new(),
            created_tools: HashMap::new(),
            next_id: 0,
        }
    }

    /// Create with default configuration.
    pub fn default_pipeline() -> Self {
        Self::new(ToolCreationConfig::default())
    }

    /// Get the pipeline configuration.
    pub fn config(&self) -> &ToolCreationConfig {
        &self.config
    }

    /// Number of created tools currently registered.
    pub fn created_count(&self) -> usize {
        self.created_tools.len()
    }

    /// Total creation attempts (successful + failed).
    pub fn total_attempts(&self) -> usize {
        self.attempts.len()
    }

    /// Successful creations.
    pub fn successful_count(&self) -> usize {
        self.attempts.iter().filter(|a| a.success).count()
    }

    /// Get a created tool by name.
    pub fn get_created_tool(&self, name: &str) -> Option<&ToolSpec> {
        self.created_tools.get(name)
    }

    /// List all created tool names.
    pub fn created_tool_names(&self) -> Vec<&str> {
        self.created_tools.keys().map(|s| s.as_str()).collect()
    }

    // ---- Main API ----

    /// Parse and validate a tool creation request from model output.
    ///
    /// Returns `Some(CreationAttempt)` if a [tool_create] block was found,
    /// `None` if no tool creation was requested.
    pub fn process_creation(
        &mut self,
        model_output: &str,
    ) -> Option<&CreationAttempt> {
        let spec = ToolSpec::parse_from_output(model_output)?;
        self.create_tool(spec);
        self.attempts.last()
    }

    /// Full tool creation pipeline: validate → register.
    ///
    /// This is the main entry point. Validates the spec, and if it passes,
    /// registers it in the created tools map. Returns the creation attempt.
    pub fn create_tool(&mut self, spec: ToolSpec) -> CreationAttempt {
        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0);

        let attempt_num = self.attempts.len() + 1;

        // Run validation
        let validation = self.validate_spec(&spec);

        let attempt = CreationAttempt {
            attempt: attempt_num,
            quality: validation.quality,
            success: validation.passed,
            errors: validation.errors.clone(),
            timestamp,
            spec: spec.clone(),
        };

        if validation.passed {
            self.created_tools.insert(spec.name.clone(), spec);
            self.next_id += 1;
            tracing::info!(
                event = "tool_created",
                name = %attempt.spec.name,
                quality = %attempt.quality,
                "Created and registered new tool"
            );
        } else {
            tracing::warn!(
                event = "tool_creation_failed",
                name = %spec.name,
                errors = ?validation.errors,
                "Tool creation failed validation"
            );
        }

        self.attempts.push(attempt.clone());
        attempt
    }

    /// Refine a failed tool spec (for retry loop).
    ///
    /// Returns a new spec with error information appended as comments
    /// so the model can read the errors and fix its code.
    pub fn format_refinement_prompt(&self, attempt: &CreationAttempt) -> String {
        let mut prompt = format!(
            "The tool '{}' failed validation (attempt {}, quality: {:.2}).\nErrors:\n",
            attempt.spec.name,
            attempt.attempt,
            attempt.quality,
        );
        for err in &attempt.errors {
            prompt.push_str(&format!("- {}\n", err));
        }
        prompt.push_str("\nOriginal code:\n");
        prompt.push_str(&attempt.spec.code);
        prompt.push_str("\n\nPlease fix the errors and create an improved version:\n");
        prompt.push_str("[tool_create]\n");
        prompt.push_str(&format!("name: {}\n", attempt.spec.name));
        prompt.push_str(&format!("description: {}\n", attempt.spec.description));
        prompt.push_str("---\n");
        prompt.push_str("// Fix the above errors...\n");
        prompt.push_str("[/tool_create]");
        prompt
    }

    /// Create a tool from a spec, with automatic refinement loop.
    ///
    /// On failure, returns the error prompt for the model to retry.
    /// Returns `None` if the spec can't even be parsed.
    pub fn create_with_refinement<F>(
        &mut self,
        spec: ToolSpec,
        generate_fn: F,
    ) -> CreationAttempt
    where
        F: Fn(&str) -> String,
    {
        // First attempt
        let mut attempt = self.create_tool(spec);
        let mut attempts = 1;

        // Refinement loop
        while !attempt.success && attempts < self.config.max_attempts {
            let refinement_prompt = self.format_refinement_prompt(&attempt);
            let model_output = generate_fn(&refinement_prompt);

            if let Some(refined_spec) = ToolSpec::parse_from_output(&model_output) {
                attempt = self.create_tool(refined_spec);
                attempts += 1;
            } else {
                // Model didn't produce a valid tool_create block
                attempt.errors.push("Model did not produce a valid [tool_create] block in refinement".into());
                break;
            }
        }

        attempt
    }

    // ---- Validation ----

    /// Validate a tool specification.
    pub fn validate_spec(&self, spec: &ToolSpec) -> ValidationResult {
        let mut checks = Vec::new();
        let mut errors = Vec::new();
        let mut warnings = Vec::new();
        let mut total_score = 0.0f32;
        let mut check_count = 0;

        // Check 1: Name validity
        let name_valid = self.validate_name(&spec.name);
        checks.push(name_valid.clone());
        if !name_valid.passed {
            errors.push(name_valid.message.clone());
        }
        total_score += name_valid.score;
        check_count += 1;

        // Check 2: Code non-empty and within size
        let code_valid = self.validate_code(&spec.code);
        checks.push(code_valid.clone());
        if !code_valid.passed {
            errors.push(code_valid.message.clone());
        }
        total_score += code_valid.score;
        check_count += 1;

        // Check 3: Description non-empty
        let desc_valid = if spec.description.is_empty() {
            warnings.push("Tool has no description".into());
            ValidationCheck {
                name: "description".into(),
                passed: true,
                score: 0.5,
                message: "Description is empty (warning)".into(),
            }
        } else {
            ValidationCheck {
                name: "description".into(),
                passed: true,
                score: 1.0,
                message: "Description provided".into(),
            }
        };
        checks.push(desc_valid);
        check_count += 1;

        // Check 4: Structural validity (balanced braces, no obviously broken code)
        let structural = self.validate_structure(&spec.code);
        checks.push(structural.clone());
        if !structural.passed {
            errors.push(structural.message.clone());
        }
        total_score += structural.score;
        check_count += 1;

        // Check 5: Safety check (no forbidden operations)
        let safety = self.validate_safety(&spec.code);
        checks.push(safety.clone());
        if !safety.passed {
            errors.push(safety.message.clone());
        }
        total_score += safety.score;
        check_count += 1;

        // Check 6: Syntax validation (if enabled)
        if self.config.validate_syntax {
            let syntax = self.validate_syntax(&spec.code);
            checks.push(syntax.clone());
            if !syntax.passed {
                errors.push(syntax.message.clone());
            }
            total_score += syntax.score;
            check_count += 1;
        }

        let quality = if check_count > 0 {
            total_score / check_count as f32
        } else {
            0.0
        };

        let passed = errors.is_empty() && quality >= self.config.quality_threshold;

        ValidationResult {
            passed,
            quality,
            checks,
            errors,
            warnings,
        }
    }

    fn validate_name(&self, name: &str) -> ValidationCheck {
        // Must be non-empty
        if name.is_empty() {
            return ValidationCheck {
                name: "name".into(),
                passed: false,
                score: 0.0,
                message: "Tool name cannot be empty".into(),
            };
        }

        // Must be alphanumeric + underscore
        if !name.chars().all(|c| c.is_alphanumeric() || c == '_') {
            return ValidationCheck {
                name: "name".into(),
                passed: false,
                score: 0.0,
                message: format!("Tool name '{}' contains invalid characters (use alphanumeric + underscore)", name),
            };
        }

        // Must not start with digit
        if name.starts_with(|c: char| c.is_ascii_digit()) {
            return ValidationCheck {
                name: "name".into(),
                passed: false,
                score: 0.0,
                message: "Tool name cannot start with a digit".into(),
            };
        }

        // Must not be reserved
        if self.config.reserved_names.contains(&name.to_string()) {
            return ValidationCheck {
                name: "name".into(),
                passed: false,
                score: 0.0,
                message: format!("Tool name '{}' is reserved", name),
            };
        }

        ValidationCheck {
            name: "name".into(),
            passed: true,
            score: 1.0,
            message: "Name is valid".into(),
        }
    }

    fn validate_code(&self, code: &str) -> ValidationCheck {
        if code.trim().is_empty() {
            return ValidationCheck {
                name: "code_empty".into(),
                passed: false,
                score: 0.0,
                message: "Tool code cannot be empty".into(),
            };
        }

        if code.len() > self.config.max_code_bytes {
            return ValidationCheck {
                name: "code_size".into(),
                passed: false,
                score: 0.0,
                message: format!(
                    "Tool code exceeds maximum size ({} > {} bytes)",
                    code.len(),
                    self.config.max_code_bytes
                ),
            };
        }

        ValidationCheck {
            name: "code".into(),
            passed: true,
            score: 1.0,
            message: "Code size valid".into(),
        }
    }

    fn validate_structure(&self, code: &str) -> ValidationCheck {
        let mut brace_depth = 0i32;
        let mut paren_depth = 0i32;
        let mut bracket_depth = 0i32;

        for ch in code.chars() {
            match ch {
                '{' => brace_depth += 1,
                '}' => brace_depth -= 1,
                '(' => paren_depth += 1,
                ')' => paren_depth -= 1,
                '[' => bracket_depth += 1,
                ']' => bracket_depth -= 1,
                _ => {}
            }
            if brace_depth < 0 || paren_depth < 0 || bracket_depth < 0 {
                return ValidationCheck {
                    name: "structure".into(),
                    passed: false,
                    score: 0.1,
                    message: "Unbalanced delimiters in code".into(),
                };
            }
        }

        if brace_depth != 0 || paren_depth != 0 || bracket_depth != 0 {
            return ValidationCheck {
                name: "structure".into(),
                passed: false,
                score: 0.2,
                message: format!(
                    "Unbalanced delimiters: braces={}, parens={}, brackets={}",
                    brace_depth, paren_depth, bracket_depth
                ),
            };
        }

        // Check that there's at least one function definition
        let has_fn = code.contains("fn ") || code.contains("function ") || code.contains("def ");
        let score = if has_fn { 1.0 } else { 0.6 };

        ValidationCheck {
            name: "structure".into(),
            passed: true,
            score,
            message: if has_fn {
                "Structure valid, function found".into()
            } else {
                "Structure valid but no function definition found".into()
            },
        }
    }

    fn validate_safety(&self, code: &str) -> ValidationCheck {
        let forbidden = [
            ("unsafe", "unsafe code block"),
            ("std::fs", "filesystem access"),
            ("std::net", "network access"),
            ("std::process", "process spawning"),
            ("std::thread", "thread creation"),
            ("::spawn", "spawning processes/threads"),
            ("::system(", "system command execution"),
            ("extern ", "external function calls"),
            ("dlopen", "dynamic library loading"),
            ("raw pointer", "raw pointer manipulation"),
            ("transmute", "memory type transmutation"),
        ];

        let lower = code.to_lowercase();
        let mut violations: Vec<String> = Vec::new();

        for (pattern, desc) in &forbidden {
            if lower.contains(pattern) {
                violations.push(desc.to_string());
            }
        }

        if violations.is_empty() {
            ValidationCheck {
                name: "safety".into(),
                passed: true,
                score: 1.0,
                message: "No forbidden operations detected".into(),
            }
        } else {
            ValidationCheck {
                name: "safety".into(),
                passed: false,
                score: 0.0,
                message: format!("Forbidden operations: {}", violations.join(", ")),
            }
        }
    }

    fn validate_syntax(&self, code: &str) -> ValidationCheck {
        // Lightweight syntax check: try to detect common issues
        // In production, this would use the WASM sandbox to compile
        let has_unterminated_string = {
            let mut in_string = false;
            let mut escape = false;
            for ch in code.chars() {
                if escape {
                    escape = false;
                    continue;
                }
                if ch == '\\' {
                    escape = true;
                    continue;
                }
                if ch == '"' {
                    in_string = !in_string;
                }
            }
            in_string // If still in string, it's unterminated
        };

        if has_unterminated_string {
            return ValidationCheck {
                name: "syntax".into(),
                passed: false,
                score: 0.1,
                message: "Unterminated string literal".into(),
            };
        }

        ValidationCheck {
            name: "syntax".into(),
            passed: true,
            score: 1.0,
            message: "Basic syntax check passed".into(),
        }
    }

    // ---- Query ----

    /// Get creation statistics.
    pub fn stats(&self) -> ToolCreationStats {
        let total = self.attempts.len();
        let successful = self.attempts.iter().filter(|a| a.success).count();
        let failed = total - successful;
        let avg_quality = if successful > 0 {
            self.attempts
                .iter()
                .filter(|a| a.success)
                .map(|a| a.quality)
                .sum::<f32>()
                / successful as f32
        } else {
            0.0
        };

        ToolCreationStats {
            total_attempts: total,
            successful,
            failed,
            avg_quality,
            tools_registered: self.created_tools.len(),
        }
    }

    /// Get all attempts for a specific tool name.
    pub fn attempts_for(&self, name: &str) -> Vec<&CreationAttempt> {
        self.attempts
            .iter()
            .filter(|a| a.spec.name == name)
            .collect()
    }
}

// ---------------------------------------------------------------------------
// Stats
// ---------------------------------------------------------------------------

/// Statistics about tool creation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ToolCreationStats {
    pub total_attempts: usize,
    pub successful: usize,
    pub failed: usize,
    pub avg_quality: f32,
    pub tools_registered: usize,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn make_spec(name: &str, code: &str) -> ToolSpec {
        ToolSpec {
            name: name.to_string(),
            description: format!("Tool {}", name),
            parameters: "input: string".into(),
            returns: "string".into(),
            code: code.to_string(),
            category: "test".into(),
            tags: vec!["test".into()],
        }
    }

    #[test]
    fn test_parse_tool_create_block() {
        let output = r#"
I need to create a tool for this.

[tool_create]
name: parse_csv
description: Parse CSV string into rows
params: input: string
returns: array
category: parser
tags: parser, csv
---
fn parse_csv(s) {
    s.split(",").collect()
}
[/tool_create]

Let me know if that works.
"#;
        let spec = ToolSpec::parse_from_output(output).unwrap();
        assert_eq!(spec.name, "parse_csv");
        assert_eq!(spec.description, "Parse CSV string into rows");
        assert_eq!(spec.parameters, "input: string");
        assert_eq!(spec.returns, "array");
        assert_eq!(spec.category, "parser");
        assert!(spec.code.contains("fn parse_csv"));
        assert_eq!(spec.tags, vec!["parser", "csv"]);
    }

    #[test]
    fn test_parse_tool_create_no_block() {
        let output = "Just a regular output with no tool creation.";
        assert!(ToolSpec::parse_from_output(output).is_none());
    }

    #[test]
    fn test_parse_tool_create_empty_name() {
        let output = "[tool_create]\n---\nfn foo() {}\n[/tool_create]";
        assert!(ToolSpec::parse_from_output(output).is_none());
    }

    #[test]
    fn test_create_tool_success() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();
        let spec = make_spec("csv_parser", "fn parse(s) { s.split(\",\") }");

        let attempt = pipeline.create_tool(spec);
        assert!(attempt.success);
        assert!(attempt.quality >= 0.7);
        assert_eq!(pipeline.created_count(), 1);
    }

    #[test]
    fn test_create_tool_reserved_name() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();
        let spec = make_spec("calm_execute", "fn foo() { 42 }");

        let attempt = pipeline.create_tool(spec);
        assert!(!attempt.success);
        assert!(attempt.errors.iter().any(|e| e.contains("reserved")));
    }

    #[test]
    fn test_create_tool_empty_code() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();
        let spec = make_spec("empty", "");

        let attempt = pipeline.create_tool(spec);
        assert!(!attempt.success);
    }

    #[test]
    fn test_create_tool_code_too_large() {
        let config = ToolCreationConfig {
            max_code_bytes: 10,
            ..Default::default()
        };
        let mut pipeline = ToolCreationPipeline::new(config);
        let spec = make_spec("big_tool", "fn tool() { very long code that exceeds the limit }");

        let attempt = pipeline.create_tool(spec);
        assert!(!attempt.success);
    }

    #[test]
    fn test_create_tool_unsafe_code() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();
        let spec = make_spec("hack", "unsafe { std::fs::read_to_string(\"/etc/passwd\") }");

        let attempt = pipeline.create_tool(spec);
        assert!(!attempt.success);
        assert!(attempt.errors.iter().any(|e| e.contains("forbidden") || e.contains("unsafe")));
    }

    #[test]
    fn test_create_tool_unbalanced_braces() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();
        let spec = make_spec("broken", "fn tool() { {{{ ");

        let attempt = pipeline.create_tool(spec);
        assert!(!attempt.success);
    }

    #[test]
    fn test_create_tool_invalid_name() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();
        let spec = make_spec("my-tool!", "fn tool() { 42 }");

        let attempt = pipeline.create_tool(spec);
        assert!(!attempt.success);
    }

    #[test]
    fn test_create_tool_name_starts_with_digit() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();
        let spec = make_spec("1tool", "fn tool() { 42 }");

        let attempt = pipeline.create_tool(spec);
        assert!(!attempt.success);
    }

    #[test]
    fn test_process_creation_from_output() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();
        let output = "[tool_create]\nname: helper\n---\nfn helper() { 42 }\n[/tool_create]";

        let attempt = pipeline.process_creation(output);
        assert!(attempt.is_some());
        assert!(attempt.unwrap().success);
    }

    #[test]
    fn test_process_creation_no_block() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();
        let output = "No tool creation here.";

        let attempt = pipeline.process_creation(output);
        assert!(attempt.is_none());
    }

    #[test]
    fn test_refinement_prompt() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();
        let spec = make_spec("broken_tool", "{{{");

        let attempt = pipeline.create_tool(spec);
        let prompt = pipeline.format_refinement_prompt(&attempt);

        assert!(prompt.contains("broken_tool"));
        assert!(prompt.contains("[tool_create]"));
        assert!(prompt.contains("[/tool_create]"));
    }

    #[test]
    fn test_create_with_refinement() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();

        // First spec is broken, but the "model" returns a fixed version
        let spec = make_spec("refine_test", "{{{");
        let attempt = pipeline.create_with_refinement(spec, |_prompt| {
            // Simulate model returning a fixed tool
            format!("[tool_create]\nname: refine_test\n---\nfn refine_test() {{ 42 }}\n[/tool_create]")
        });

        assert!(attempt.success);
    }

    #[test]
    fn test_create_with_refinement_max_attempts() {
        let config = ToolCreationConfig {
            max_attempts: 2,
            ..Default::default()
        };
        let mut pipeline = ToolCreationPipeline::new(config);

        let spec = make_spec("never_works", "unsafe { boom }");
        let attempt = pipeline.create_with_refinement(spec, |_prompt| {
            // Model keeps producing unsafe code
            "[tool_create]\nname: never_works\n---\nunsafe { still_broken }\n[/tool_create]".to_string()
        });

        assert!(!attempt.success);
        assert!(pipeline.total_attempts() <= 3); // initial + 2 refinements
    }

    #[test]
    fn test_stats() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();

        pipeline.create_tool(make_spec("good1", "fn good1() { 1 }"));
        pipeline.create_tool(make_spec("good2", "fn good2() { 2 }"));
        pipeline.create_tool(make_spec("bad", "unsafe { 3 }"));

        let stats = pipeline.stats();
        assert_eq!(stats.total_attempts, 3);
        assert_eq!(stats.successful, 2);
        assert_eq!(stats.failed, 1);
        assert!(stats.avg_quality > 0.0);
        assert_eq!(stats.tools_registered, 2);
    }

    #[test]
    fn test_attempts_for() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();
        pipeline.create_tool(make_spec("multi", "fn v1() { 1 }"));

        // Manually add a second attempt for the same name
        let spec = make_spec("multi", "fn v2() { 2 }");
        pipeline.create_tool(spec);

        let attempts = pipeline.attempts_for("multi");
        assert_eq!(attempts.len(), 2);
    }

    #[test]
    fn test_get_created_tool() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();
        pipeline.create_tool(make_spec("lookup_test", "fn f() { 42 }"));

        let tool = pipeline.get_created_tool("lookup_test").unwrap();
        assert_eq!(tool.name, "lookup_test");
        assert!(pipeline.get_created_tool("nonexistent").is_none());
    }

    #[test]
    fn test_created_tool_names() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();
        pipeline.create_tool(make_spec("alpha", "fn a() {}"));
        pipeline.create_tool(make_spec("beta", "fn b() {}"));

        let mut names = pipeline.created_tool_names();
        names.sort();
        assert_eq!(names, vec!["alpha", "beta"]);
    }

    #[test]
    fn test_validate_description_warning() {
        let pipeline = ToolCreationPipeline::default_pipeline();
        let spec = ToolSpec {
            name: "no_desc".into(),
            description: String::new(),
            parameters: String::new(),
            returns: String::new(),
            code: "fn no_desc() { 1 }".into(),
            category: "test".into(),
            tags: vec![],
        };

        let result = pipeline.validate_spec(&spec);
        assert!(result.warnings.iter().any(|w| w.contains("description")));
    }

    #[test]
    fn test_tool_spec_new() {
        let spec = ToolSpec::new("test", "A test tool", "fn test() {}");
        assert_eq!(spec.name, "test");
        assert_eq!(spec.category, "generated");
        assert_eq!(spec.tags, vec!["auto-generated"]);
    }

    #[test]
    fn test_unterminated_string_detection() {
        let mut pipeline = ToolCreationPipeline::default_pipeline();
        let spec = make_spec("bad_str", "fn f() { let s = \"unterminated }");

        let attempt = pipeline.create_tool(spec);
        assert!(!attempt.success);
    }
}
