pub mod pipeline;
pub mod buffer;
pub mod memory;
pub mod kernels;
pub mod cache;
pub mod turboquant;
pub mod async_pipeline;
pub mod distributed;
pub mod hardware;
pub mod transport;

pub use pipeline::WgpuCompute;
pub use buffer::GpuBuffer;
pub use memory::{MemoryBudget, MemoryPool, TiledCompute, ComputeDispatcher, DeviceMemoryPhase, BorrowedBufferPool};
pub use cache::{BlockCache, PipelineStage, PipelineScheduler};
pub use kernels::softmax::SoftmaxOp;
pub use kernels::rmsnorm::RmsNormOp;
pub use kernels::elementwise::ElementWiseOp;
pub use kernels::matmul::MatMulOp;
pub use kernels::matmul::MatMulDoubleBufferOp;
pub use kernels::moe::{MoEGatingOp, MoEExpertOp};
pub use kernels::rope::RopeOp;
pub use kernels::im2col::Im2ColOp;
pub use kernels::fused_patch_embed::FusedPatchEmbedOp;
pub use kernels::tome_merge::TomeMergeOp;
pub use kernels::flash_decode::FlashDecodeOp;
pub use kernels::flash_decode::FlashDecodeTiledOp;
pub use kernels::causal_mask::CausalMaskOp;
